export const DEFAULT_CUSTOM_AGENT_ACTIVATION_SCAN_DEPTH = 5;
export const MAX_CUSTOM_AGENT_ACTIVATION_SCAN_DEPTH = 200;
export const DEFAULT_CUSTOM_AGENT_ACTIVATION_THRESHOLD = 0.5;
export const MAX_CUSTOM_AGENT_ACTIVATION_QUESTION_LENGTH = 500;
