// Sandbox engine: the same build run against a copied, sanitized store on its own port.
//
// Isolation, in layers:
// - Own DATA_DIR / FILE_STORAGE_DIR / LOG_DIR and its own env file (MARINARA_ENV_FILE), bound to 127.0.0.1 only.
// - HOME / USERPROFILE / APPDATA / LOCALAPPDATA / XDG_* / CODEX_HOME / CLAUDE_CONFIG_DIR point into the sandbox, so
//   subscription logins (Codex/ChatGPT, Claude Code, CLI-based providers) do not exist there and every such model call
//   fails at once instead of spending quota.
// - API keys and other credential-looking fields are blanked, and remote base URLs point at a closed local port, in
//   the copied connections table. Discord and other webhooks are removed from copied chats.
// - Credential-looking environment variables of the caller are not passed on.
// - Updates cannot be applied from the sandbox (UPDATES_APPLY_DISABLED) and no default connection is seeded.
// Consequence: the sandbox is for prompt previews, UI checks, code verification and restart testing, not for real
// model replies.
import { execFileSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, isAbsolute, join, relative, resolve } from "node:path";
import { IS_WINDOWS, LIVE_DATA_DIR, SANDBOX_DIR, SANDBOX_PORT, SERVER_DIR } from "./config.mjs";
import { startDetached, writePidFile } from "./proc.mjs";

const DATA = join(SANDBOX_DIR, "data");
const STORAGE = join(DATA, "storage");
const HOME = join(SANDBOX_DIR, "home");
const ENV_FILE = join(SANDBOX_DIR, ".env");
export const SANDBOX_LOG = join(SANDBOX_DIR, "sandbox.log");
const META_FILE = join(SANDBOX_DIR, "sandbox.json");
const BLACKHOLE = "http://127.0.0.1:9/sandbox-blocked/v1";
const SECRET_FIELD = /api_?key|secret|token|password|credential/i;
const SECRET_ENV = /api_?key|token|secret|password|passwd|credential|cookie|auth|session|private_?key|encryption_?key/i;

const inside = (parent, child) => {
  const rel = relative(parent, child);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
};

/** The path with every symlink or junction resolved; for a missing path, its nearest existing ancestor's. */
function realPath(path) {
  const full = resolve(path);
  try {
    return realpathSync.native(full);
  } catch {
    const parent = resolve(full, "..");
    return parent === full ? full : join(realPath(parent), basename(full));
  }
}

/**
 * Refuse any layout where the sandbox and the live data could be the same folder or nested in each other, both as
 * written and after resolving links (a linked sandbox or live folder can make two different paths one folder).
 */
function assertSeparateFromLive() {
  const pairs = [
    [resolve(LIVE_DATA_DIR), resolve(DATA)],
    [realPath(LIVE_DATA_DIR), realPath(DATA)],
    [realPath(join(LIVE_DATA_DIR, "storage")), realPath(DATA)],
  ];
  for (const [live, sandbox] of pairs) {
    if (inside(live, sandbox) || inside(sandbox, live)) {
      throw new Error(`sandbox data (${sandbox}) must not be the live data folder (${live}) or inside it`);
    }
  }
}

/**
 * Sanitizing rewrites files in the copy, so the copy must hold only its own regular files: a symlink or junction (a
 * linked storage folder or shard copied as a link) or a hard link would carry that write into the live store.
 */
function assertIndependentCopy(root) {
  const sandboxRoot = realPath(SANDBOX_DIR);
  if (!inside(sandboxRoot, realPath(root))) throw new Error(`sandbox storage ${root} resolves outside ${sandboxRoot}`);
  const walk = (path) => {
    const info = lstatSync(path);
    if (info.isSymbolicLink()) throw new Error(`sandbox copy contains a link (${path}); refusing to sanitize through it`);
    if (info.isDirectory()) for (const name of readdirSync(path)) walk(join(path, name));
    else if (info.nlink > 1) throw new Error(`sandbox copy contains a hard-linked file (${path}); refusing to sanitize it`);
  };
  walk(root);
}

function sandboxEnv() {
  return {
    NODE_ENV: "production",
    PORT: String(SANDBOX_PORT),
    HOST: "127.0.0.1",
    DATA_DIR: DATA,
    FILE_STORAGE_DIR: STORAGE,
    LOG_DIR: join(DATA, "logs"),
    AUTO_OPEN_BROWSER: "false",
    UPDATES_APPLY_DISABLED: "true",
    AUTO_CREATE_DEFAULT_CONNECTION: "false",
  };
}

function writeEnvFile() {
  const lines = Object.entries(sandboxEnv()).map(([k, v]) => `${k}="${v.replace(/\\/g, "/")}"`);
  writeFileSync(ENV_FILE, `# Marinara sandbox (generated by tools/dev-mcp). Never point this at live data.\n${lines.join("\n")}\n`);
}

const readJson = (path) => JSON.parse(readFileSync(path, "utf8"));

/** Apply `fn` to every row of every shard of a copied table, rewriting shards that changed. */
function rewriteRows(table, fn) {
  const dir = join(STORAGE, "tables", table);
  if (!existsSync(dir)) return 0;
  let changed = 0;
  for (const name of readdirSync(dir)) {
    if (!name.endsWith(".json")) continue;
    const path = join(dir, name);
    const data = readJson(path);
    const rows = Array.isArray(data)
      ? data
      : Array.isArray(data?.rows)
        ? data.rows
        : data && typeof data === "object" && "id" in data
          ? [data]
          : Object.values(data?.rows ?? data ?? {});
    let dirty = false;
    for (const row of rows) if (row && typeof row === "object" && fn(row)) dirty = true;
    if (dirty) {
      writeFileSync(path, JSON.stringify(data));
      changed += 1;
    }
  }
  return changed;
}

function sanitize() {
  const connections = rewriteRows("api_connections", (row) => {
    let dirty = false;
    // Every credential-looking field (apiKeyEncrypted today); blanked, not deleted, so the row stays valid.
    for (const key of Object.keys(row).filter((k) => SECRET_FIELD.test(k))) {
      if (typeof row[key] === "string" && row[key]) {
        row[key] = "";
        dirty = true;
      }
    }
    // Some providers answer without a key (a public model list, keyless image services), so also point every base URL
    // at a closed local port. An empty one counts too: the engine falls back to the provider's default remote URL.
    // Subscription providers do not use the field; their logins are hidden by the home redirect.
    for (const key of Object.keys(row).filter((k) => /base_?url|endpoint/i.test(k))) {
      const value = row[key];
      const empty = value == null || (typeof value === "string" && !value.trim());
      const remote = typeof value === "string" && /^https?:[/][/]/i.test(value) && !value.includes("sandbox-blocked");
      if (empty || remote) {
        row[key] = BLACKHOLE;
        dirty = true;
      }
    }
    return dirty;
  });
  const chats = rewriteRows("chats", (row) => {
    const raw = row.metadata;
    let meta;
    try {
      meta = typeof raw === "string" ? JSON.parse(raw || "{}") : raw;
    } catch {
      return false;
    }
    if (!meta || typeof meta !== "object") return false;
    const hooks = Object.keys(meta).filter((k) => /discord|webhook/i.test(k));
    if (!hooks.length) return false;
    for (const key of hooks) delete meta[key];
    row.metadata = typeof raw === "string" ? JSON.stringify(meta) : meta;
    return true;
  });
  // A custom tool with a webhook POSTs its payload to that URL (stored encrypted, which the sandbox can decrypt with the
  // shared key), so every webhook or URL field is cleared; the tool then has nowhere to send.
  const customTools = rewriteRows("custom_tools", (row) => {
    let dirty = false;
    for (const key of Object.keys(row).filter((k) => /webhook|url|endpoint/i.test(k))) {
      if (row[key] != null && row[key] !== "") {
        row[key] = null;
        dirty = true;
      }
    }
    return dirty;
  });
  for (const name of readdirSync(STORAGE)) {
    if (name.startsWith(".writer-lease")) rmSync(join(STORAGE, name), { recursive: true, force: true });
  }
  return {
    connectionShardsSanitized: connections,
    chatShardsWithWebhooksRemoved: chats,
    customToolShardsWithWebhooksRemoved: customTools,
  };
}

const SKIP = (name) => name.endsWith(".bak") || name.endsWith(".prepaint") || name.startsWith(".writer-lease");

/** Mirror the live store into the sandbox. Windows uses robocopy (multi-threaded); elsewhere a Node copy. */
function mirror(source, target) {
  if (IS_WINDOWS) {
    let code = 0;
    try {
      execFileSync(
        "robocopy",
        [source, target, "/MIR", "/R:2", "/W:1", "/MT:8", "/NFL", "/NDL", "/NJH", "/NJS", "/NP",
          "/XF", "*.bak", "*.prepaint", ".writer-lease*", "/XD", ".writer-lease"],
        { windowsHide: true, stdio: "ignore" },
      );
    } catch (error) {
      code = typeof error.status === "number" ? error.status : 16;
    }
    // robocopy: 0-7 are success variants, 8 and above are failures.
    if (code >= 8) throw new Error(`robocopy failed with code ${code}`);
    return;
  }
  rmSync(target, { recursive: true, force: true });
  // dereference: a linked storage folder or shard is copied as independent files, never as a link to the live data.
  cpSync(source, target, { recursive: true, dereference: true, filter: (src) => !SKIP(basename(src)) });
}

/** Copy the live store (not images or other assets) into the sandbox and sanitize it. The live store is only read. */
export function refreshSandboxData() {
  assertSeparateFromLive();
  mkdirSync(DATA, { recursive: true });
  mkdirSync(HOME, { recursive: true });
  const source = join(LIVE_DATA_DIR, "storage");
  if (!existsSync(source)) throw new Error(`live storage not found at ${source}`);
  // The marker is written only after sanitizing succeeds; startSandboxProcess refuses to run without it.
  rmSync(META_FILE, { force: true });
  // A sandbox storage folder that is itself a link would make the mirror write (and delete) through it.
  if (lstatSync(STORAGE, { throwIfNoEntry: false })?.isSymbolicLink()) {
    throw new Error(`sandbox storage ${STORAGE} is a link; remove it and refresh again`);
  }
  mirror(source, STORAGE);
  assertIndependentCopy(STORAGE);
  writeEnvFile();
  const sanitized = sanitize();
  const meta = { refreshedAt: new Date().toISOString(), source, port: SANDBOX_PORT, ...sanitized };
  writeFileSync(META_FILE, JSON.stringify(meta, null, 2));
  return meta;
}

export function sandboxInfo() {
  return {
    dir: SANDBOX_DIR,
    port: SANDBOX_PORT,
    exists: existsSync(STORAGE),
    ...(existsSync(META_FILE) ? readJson(META_FILE) : {}),
    storageModified: existsSync(STORAGE) ? new Date(statSync(STORAGE).mtimeMs).toISOString() : null,
    runningDist: existsSync(join(SANDBOX_DIR, "dist.txt")) ? readFileSync(join(SANDBOX_DIR, "dist.txt"), "utf8") : null,
  };
}

/** The caller's environment without anything that looks like a credential, with every home folder redirected. */
function isolatedEnv() {
  const inherited = Object.fromEntries(Object.entries(process.env).filter(([key]) => !SECRET_ENV.test(key)));
  return {
    ...inherited,
    ...sandboxEnv(),
    MARINARA_ENV_FILE: ENV_FILE,
    HOME,
    USERPROFILE: HOME,
    APPDATA: join(HOME, "AppData", "Roaming"),
    LOCALAPPDATA: join(HOME, "AppData", "Local"),
    XDG_CONFIG_HOME: join(HOME, ".config"),
    XDG_DATA_HOME: join(HOME, ".local", "share"),
    XDG_CACHE_HOME: join(HOME, ".cache"),
    XDG_STATE_HOME: join(HOME, ".local", "state"),
    CODEX_HOME: join(HOME, ".codex"),
    CLAUDE_CONFIG_DIR: join(HOME, ".claude"),
  };
}

/**
 * Start the sandbox server (detached, output in sandbox.log) through the same run-server supervisor the launchers
 * use. The caller waits for health. `distDir` (relative to packages/server, default "dist") lets a developer test a
 * private build such as "dist-sandbox" without replacing the live engine's dist.
 */
/** The build folder the sandbox last ran (sandbox_refresh records it), so a plain restart keeps using it. */
function recordedDist() {
  try {
    const value = readFileSync(join(SANDBOX_DIR, "dist.txt"), "utf8").trim();
    return /^dist[\w-]*$/.test(value) ? value : null;
  } catch {
    return null;
  }
}

export async function startSandboxProcess(distDir = recordedDist() || process.env.MARINARA_DEV_SANDBOX_DIST || "dist") {
  if (!/^dist[\w-]*$/.test(distDir)) throw new Error(`invalid dist folder name ${distDir}`);
  if (!existsSync(join(SERVER_DIR, distDir, "index.js"))) throw new Error(`no ${distDir}/index.js in packages/server`);
  if (!existsSync(STORAGE) || !existsSync(META_FILE)) {
    throw new Error("the sandbox has no sanitized data yet; run sandbox_refresh first");
  }
  assertSeparateFromLive();
  mkdirSync(HOME, { recursive: true });
  writeFileSync(join(SANDBOX_DIR, "dist.txt"), distDir);
  writeEnvFile();
  const pid = await startDetached({
    cwd: SERVER_DIR,
    args: ["../../scripts/run-server.mjs", `${distDir}/index.js`],
    env: isolatedEnv(),
    outLog: SANDBOX_LOG,
    errLog: SANDBOX_LOG,
  });
  writePidFile(SANDBOX_PORT, pid);
  return pid;
}
